# Site settings
title: Beyond Care
email: frank@beyondcare.dk
phone: "+45 2241 6614"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Other settings
timezone: Europe/Copenhagen
include: ["_pages"]

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true

prose:
  rootUrl: "_pages"
  siteurl: "http://beyondcare.dk"
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
    - /_sass
  metadata:
    _pages:
      - name: "layout"
        field:
          element: "select"
          value: "default"
          options:
            - name: "Default"
              value: "default"
            - name: "Services"
              value: "services"
