services:
  - service: Foredrag og temadage
    url: /foredrag
    text: Om konflikthåndtering, relationskompetence og kommunikation.
  - service: Coaching
    url: /coaching
    icon: null
    text: Tillidsskabende, troværdig og utrolig dedikeret life- og businesscoach,
      der hjælper dig med at nå dine mål. Jeg er med dig hele vejen.
  - service: Massage
    url: /massage
    icon: null
    text: Erfaren og kompetent massør tilbyder forskellige former for massage.
      Herunder også muskeltests, tapening med bl.a. kinesiotape og sportstape,
      triggerpunktsterapi samt sportsakupunktur.
