contact:
  - icon: facebook
    href: https://www.facebook.com/frankknudsenbeyondcare/
    text: BeyondCare
  - icon: instagram
    href: https://www.instagram.com/coachfrankknudsen/
    text: coachfrankknudsen
  - icon: envelope-o
    href: mailto:frank@beyondcare.dk
    text: frank@beyondcare.dk
  - icon: phone
    href: "tel:+4522416614"
    text: +45 2241 6614
